version: "3.8"

services:
  eureka:
    container_name: eureka-server
    image: ${DOCKER_USERNAME}/eureka:latest
    ports:
      - "8761:8761"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true
