server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: ${EUREKA_HOST}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false