name: Deploy Eureka Server

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build JAR
        run: ./gradlew bootJar

      - name: Decode and save PEM key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > eureka-key.pem
          chmod 400 eureka-key.pem

      - name: Copy files to EC2
        run: |
          scp -i eureka-key.pem -o StrictHostKeyChecking=no \
            build/libs/*.jar \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/eureka.jar

          scp -i eureka-key.pem -o StrictHostKeyChecking=no \
            Dockerfile docker-compose.yml .env \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/

      - name: Remote SSH and deploy
        run: |
          ssh -i eureka-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            docker compose down
            docker compose build
            docker compose up -d
          EOF